### ISSUE TITLE
Deceptive Site Error for brow.sh

### ISSUE THREAD

**Issue by abdulhannanali** [browsh-org/www.brow.sh#2] opened 2018-07-09 07:25 UTC
Firefox 60 on Ubuntu displays a Deceptive Site error which means this is in the Google Safe Browsing List. I have reported it to the firefox. I hope other people can do it too. So we can get it removed :) 

![image](https://user-images.githubusercontent.com/8170969/42436353-198984fc-8373-11e8-9399-86c1c74e004c.png)

**Comment by tombh** [comment] 2018-07-09 07:38
This is caused by the fact that the live HTML service can render sites like: https://html.brow.sh/http://mail.google.com Google then detects that as an attempt to phish Gmail user's usernames and passwords. The HTML service only returns plain text, <pre> & <a> tags, not even any JS. So it's actually impossible for a phishing attack to occur.

I've disabled the HTML services ability to parse Gmail now and submitted a review to Google a few hours ago. But Google said it could take up to 72 hours :/

**Comment by tombh** [comment] 2018-07-12 04:58
This should be fixed now: https://www.virustotal.com/#/url/54ab74be93601eb2f252364829ce5a61a8840f52c0f4cfe7a09f0c32730b8c85/detection

**Closed by tombh** 2018-07-12 04:58 UTC
